### ISSUE TITLE
NameError: name 'Checkpointer' is not defined

### ISSUE THREAD

**Issue by hstko** [r-three/mats#1]
I followed the instructions in the README and executed the following command, but encountered an error: "ModuleNotFoundError: No module named 'src.model.Checkpointer'".

Command executed:

`python src/training.py -c configs/models/t5_large.json configs/training_run/individual_task_T0_run.json  configs/training_dataset/p3_individual_task.json configs/evaluation_dataset/p3_validation.json configs/evaluation_run/individual_task.json -td train_dataset=paws -ed evaluation_dataset=paws  -tr micro_train_batch_size=16  -er eval_batch_size=32`

**Comment by 123epsilon** [comment]
I'm trying to reproduce some of the results from the paper and I'm having the same issue, there is indeed no module by that name and I can't seem to find this class anywhere else in the repo. There is a pyc cache in the repo that's checked in, so I'm guessing this is a class that was never committed when uploading this repository. Is it possible to fix this @dptam?

**Comment by dptam** [comment]
Hi @hstko and @123epsilon, thank you for letting me know. I just added the `Checkpointer.py` class. Let me know if there are any other issues!

**Comment by hstko** [comment]
thank you.
